name: .NET Core Workflow

on: [push]
jobs: 
  run:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    env:
      OS: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: 5.0.x

    - name: Restore Dependencies
      run: dotnet restore Vivian.sln

    - name: Build Solution
      run: dotnet build Vivian.sln --no-restore --nologo
    
    - name: Generate Coverage Report
      run: dotnet test src/Vivian.Tests --no-build --verbosity normal
